language: python
sudo: false
dist: trusty

addons:
  apt:
    packages:
     - python-pip
     - xsltproc
     - enscript
     - ghostscript
     - pandoc
     - python-pandocfilters
     - texlive-latex-base

env:
  global:
   - GOPATH="${TRAVIS_BUILD_DIR}/.go_workspace"
   - mmark_src=github.com/miekg/mmark/mmark
   - mmark=./mmark

install:
 - pip install xml2rfc
 - if head -1 -q *.md | grep '^\-\-\-' >/dev/null 2>&1; then gem install --no-doc kramdown-rfc2629; fi
 - if head -1 -q *.md | grep '^%%%' >/dev/null 2>&1; then go get "$mmark_src" && go build "$mmark_src"; fi

script:
 - cd slides; make; cd ..;
 - make ghpages

after_success:
 - mkdir public
 - cd public
 - mv ../*.txt ../*.html ../*.pdf ../slides/*.pdf .
 - ../.travisci/make-index.py . > index.html
 - cd ..

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # set this in travis-ci dashboard
  on:
    branch: master
  local_dir: public