language: python
sudo: false
dist: trusty

addons:
  apt:
    packages:
     - python-pip
     - xsltproc
     - enscript
     - ghostscript
     - pandoc
#     - texlive-latex-base
#     - latex-beamer

env:
  global:
   - GOPATH="${TRAVIS_BUILD_DIR}/.go_workspace"
   - mmark_src=github.com/miekg/mmark/mmark
   - mmark=./mmark

install:
 - echo "deb http://archive.ubuntu.com/ubuntu cosmic main restricted" > /etc/apt/sources.list
 - echo "deb http://archive.ubuntu.com/ubuntu cosmic-updates main restricted" >> /etc/apt/sources.list
 - echo "deb http://archive.ubuntu.com/ubuntu cosmic universe" >> /etc/apt/sources.list
 - echo "deb http://archive.ubuntu.com/ubuntu cosmic-updates universe" >> /etc/apt/sources.list
 - echo "deb http://archive.ubuntu.com/ubuntu cosmic multiverse" >> /etc/apt/sources.list
 - echo "deb http://archive.ubuntu.com/ubuntu cosmic-updates multiverse" >> /etc/apt/sources.list
 - echo "deb http://archive.ubuntu.com/ubuntu cosmic-backports main restricted universe multiverse" >> /etc/apt/sources.list
 - echo "deb http://security.ubuntu.com/ubuntu cosmic-security main" >> /etc/apt/sources.list
 - echo "deb http://security.ubuntu.com/ubuntu cosmic-security universe" >> /etc/apt/sources.list
 - apt-get update
 - apt-get install dpkg
 - dpkg -r bash-completion
 - apt-get install pandoc
 - apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra
 - pip install xml2rfc
 - if head -1 -q *.md | grep '^\-\-\-' >/dev/null 2>&1; then gem install --no-doc kramdown-rfc2629; fi
 - if head -1 -q *.md | grep '^%%%' >/dev/null 2>&1; then go get "$mmark_src" && go build "$mmark_src"; fi

script:
 - make
 - make pdf
 - cd slides; make; cd ..;

after_success:
 - mkdir public
 - cd public
 - mv ../*.txt ../*.html ../*.pdf ../slides/*.pdf .
 - ../.travisci/make-index.py . > index.html
 - cd ..

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # set this in travis-ci dashboard
  on:
    branch: master
  local_dir: public
